title: Webb Kimmel # your name (or website title) here
logo: "/images/IMG_0639 small.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst looking for opportunities <br><br> 
  Unique background in business, outdoor recreation and customer service  <br><br>
  Outdoor enthusiast, raft guide, reader <br><br>
  <a href="https://www.linkedin.com/in/webb-kimmel-346701a8/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
